spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registrations
    username: root
    password: '@Potter77'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: update
        
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level: 
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type]": TRACE
    